---
driver:
  name: hyperv
  parent_vhd_folder: D:\Hyper-V\windows-2012-r2
  parent_vhd_name: Win2012r2-Disk0.vhdx
  vm_generation: 2
  vm_switch: LabNetwork
  memory_startup_bytes: 2GB

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012-r2

transport:
  name: winrm
  elevated: true
  password: somethingiwontwritehere

suites:
  - name: default
    run_list:
      - recipe[my_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
